using System.Collections.Generic;
using InControl;
using Platform;
using UnityEngine;

namespace GUI_2;

public static class UIUtils
{
	public enum ButtonIcon
	{
		FaceButtonSouth,
		FaceButtonNorth,
		FaceButtonEast,
		FaceButtonWest,
		ConfirmButton,
		CancelButton,
		LeftBumper,
		RightBumper,
		LeftTrigger,
		RightTrigger,
		LeftStick,
		LeftStickUpDown,
		LeftStickLeftRight,
		LeftStickButton,
		LeftStickLeft,
		LeftStickRight,
		LeftStickUp,
		LeftStickDown,
		RightStick,
		RightStickUpDown,
		RightStickLeftRight,
		RightStickButton,
		RightStickLeft,
		RightStickRight,
		RightStickUp,
		RightStickDown,
		DPadLeft,
		DPadRight,
		DPadUp,
		DPadDown,
		StartButton,
		BackButton,
		None,
		Count
	}

	[PublicizedFrom(EAccessModifier.Private)]
	public static INGUIAtlas symbolAtlas;

	[PublicizedFrom(EAccessModifier.Private)]
	public static readonly Dictionary<ButtonIcon, string> buttonIconMapPS = new EnumDictionary<ButtonIcon, string>
	{
		{
			ButtonIcon.FaceButtonSouth,
			"PS5_Button_Action1"
		},
		{
			ButtonIcon.FaceButtonNorth,
			"PS5_Button_Action4"
		},
		{
			ButtonIcon.FaceButtonEast,
			"PS5_Button_Action2"
		},
		{
			ButtonIcon.FaceButtonWest,
			"PS5_Button_Action3"
		},
		{
			ButtonIcon.ConfirmButton,
			"PS5_Button_Action1"
		},
		{
			ButtonIcon.CancelButton,
			"PS5_Button_Action2"
		},
		{
			ButtonIcon.LeftBumper,
			"PS5_Button_LeftBumper"
		},
		{
			ButtonIcon.LeftTrigger,
			"PS5_Button_LeftTrigger"
		},
		{
			ButtonIcon.RightBumper,
			"PS5_Button_RightBumper"
		},
		{
			ButtonIcon.RightTrigger,
			"PS5_Button_RightTrigger"
		},
		{
			ButtonIcon.LeftStick,
			"PS5_Button_LeftStick"
		},
		{
			ButtonIcon.LeftStickUpDown,
			"PS5_Button_LeftStickUpDown"
		},
		{
			ButtonIcon.LeftStickLeftRight,
			"PS5_Button_LeftStickLeftRight"
		},
		{
			ButtonIcon.LeftStickButton,
			"PS5_Button_LeftStickButton"
		},
		{
			ButtonIcon.LeftStickLeft,
			"PS5_Button_LeftStickLeft"
		},
		{
			ButtonIcon.LeftStickRight,
			"PS5_Button_LeftStickRight"
		},
		{
			ButtonIcon.LeftStickDown,
			"PS5_Button_LeftStickDown"
		},
		{
			ButtonIcon.LeftStickUp,
			"PS5_Button_LeftStickUp"
		},
		{
			ButtonIcon.RightStick,
			"PS5_Button_RightStick"
		},
		{
			ButtonIcon.RightStickUpDown,
			"PS5_Button_RightStickUpDown"
		},
		{
			ButtonIcon.RightStickLeftRight,
			"PS5_Button_RightStickLeftRight"
		},
		{
			ButtonIcon.RightStickButton,
			"PS5_Button_RightStickButton"
		},
		{
			ButtonIcon.RightStickLeft,
			"PS5_Button_RightStickLeft"
		},
		{
			ButtonIcon.RightStickRight,
			"PS5_Button_RightStickRight"
		},
		{
			ButtonIcon.RightStickDown,
			"PS5_Button_RightStickDown"
		},
		{
			ButtonIcon.RightStickUp,
			"PS5_Button_RightStickUp"
		},
		{
			ButtonIcon.DPadLeft,
			"PS5_Button_DPadLeft"
		},
		{
			ButtonIcon.DPadRight,
			"PS5_Button_DPadRight"
		},
		{
			ButtonIcon.DPadUp,
			"PS5_Button_DPadUp"
		},
		{
			ButtonIcon.DPadDown,
			"PS5_Button_DPadDown"
		},
		{
			ButtonIcon.StartButton,
			"PS5_Button_Start"
		},
		{
			ButtonIcon.BackButton,
			"PS5_Button_Back"
		},
		{
			ButtonIcon.None,
			""
		}
	};

	[PublicizedFrom(EAccessModifier.Private)]
	public static readonly Dictionary<ButtonIcon, string> buttonIconMapXB = new EnumDictionary<ButtonIcon, string>
	{
		{
			ButtonIcon.FaceButtonSouth,
			"XB_Button_Action1"
		},
		{
			ButtonIcon.FaceButtonNorth,
			"XB_Button_Action4"
		},
		{
			ButtonIcon.FaceButtonEast,
			"XB_Button_Action2"
		},
		{
			ButtonIcon.FaceButtonWest,
			"XB_Button_Action3"
		},
		{
			ButtonIcon.ConfirmButton,
			"XB_Button_Action1"
		},
		{
			ButtonIcon.CancelButton,
			"XB_Button_Action2"
		},
		{
			ButtonIcon.LeftBumper,
			"XB_Button_LeftBumper"
		},
		{
			ButtonIcon.LeftTrigger,
			"XB_Button_LeftTrigger"
		},
		{
			ButtonIcon.RightBumper,
			"XB_Button_RightBumper"
		},
		{
			ButtonIcon.RightTrigger,
			"XB_Button_RightTrigger"
		},
		{
			ButtonIcon.LeftStick,
			"XB_Button_LeftStick"
		},
		{
			ButtonIcon.LeftStickUpDown,
			"XB_Button_LeftStickUpDown"
		},
		{
			ButtonIcon.LeftStickLeftRight,
			"XB_Button_LeftStickLeftRight"
		},
		{
			ButtonIcon.LeftStickButton,
			"XB_Button_LeftStickButton"
		},
		{
			ButtonIcon.LeftStickLeft,
			"XB_Button_LeftStickLeft"
		},
		{
			ButtonIcon.LeftStickRight,
			"XB_Button_LeftStickRight"
		},
		{
			ButtonIcon.LeftStickDown,
			"XB_Button_LeftStickDown"
		},
		{
			ButtonIcon.LeftStickUp,
			"XB_Button_LeftStickUp"
		},
		{
			ButtonIcon.RightStick,
			"XB_Button_RightStick"
		},
		{
			ButtonIcon.RightStickUpDown,
			"XB_Button_RightStickUpDown"
		},
		{
			ButtonIcon.RightStickLeftRight,
			"XB_Button_RightStickLeftRight"
		},
		{
			ButtonIcon.RightStickButton,
			"XB_Button_RightStickButton"
		},
		{
			ButtonIcon.RightStickLeft,
			"XB_Button_RightStickLeft"
		},
		{
			ButtonIcon.RightStickRight,
			"XB_Button_RightStickRight"
		},
		{
			ButtonIcon.RightStickDown,
			"XB_Button_RightStickDown"
		},
		{
			ButtonIcon.RightStickUp,
			"XB_Button_RightStickUp"
		},
		{
			ButtonIcon.DPadLeft,
			"XB_Button_DPadLeft"
		},
		{
			ButtonIcon.DPadRight,
			"XB_Button_DPadRight"
		},
		{
			ButtonIcon.DPadUp,
			"XB_Button_DPadUp"
		},
		{
			ButtonIcon.DPadDown,
			"XB_Button_DPadDown"
		},
		{
			ButtonIcon.StartButton,
			"XB_Button_Menu"
		},
		{
			ButtonIcon.BackButton,
			"XB_Button_Back"
		},
		{
			ButtonIcon.None,
			""
		}
	};

	[PublicizedFrom(EAccessModifier.Private)]
	public static readonly Dictionary<InputControlType, ButtonIcon> iconControlMap = new EnumDictionary<InputControlType, ButtonIcon>
	{
		{
			InputControlType.Action1,
			ButtonIcon.FaceButtonSouth
		},
		{
			InputControlType.Action2,
			ButtonIcon.FaceButtonEast
		},
		{
			InputControlType.Action3,
			ButtonIcon.FaceButtonWest
		},
		{
			InputControlType.Action4,
			ButtonIcon.FaceButtonNorth
		},
		{
			InputControlType.LeftBumper,
			ButtonIcon.LeftBumper
		},
		{
			InputControlType.RightBumper,
			ButtonIcon.RightBumper
		},
		{
			InputControlType.LeftTrigger,
			ButtonIcon.LeftTrigger
		},
		{
			InputControlType.RightTrigger,
			ButtonIcon.RightTrigger
		},
		{
			InputControlType.LeftStickButton,
			ButtonIcon.LeftStickButton
		},
		{
			InputControlType.LeftStickX,
			ButtonIcon.LeftStickLeftRight
		},
		{
			InputControlType.LeftStickY,
			ButtonIcon.LeftStickUpDown
		},
		{
			InputControlType.LeftStickLeft,
			ButtonIcon.LeftStickLeft
		},
		{
			InputControlType.LeftStickRight,
			ButtonIcon.LeftStickRight
		},
		{
			InputControlType.LeftStickDown,
			ButtonIcon.LeftStickDown
		},
		{
			InputControlType.LeftStickUp,
			ButtonIcon.LeftStickUp
		},
		{
			InputControlType.RightStickButton,
			ButtonIcon.RightStickButton
		},
		{
			InputControlType.RightStickX,
			ButtonIcon.RightStickLeftRight
		},
		{
			InputControlType.RightStickY,
			ButtonIcon.RightStickUpDown
		},
		{
			InputControlType.RightStickLeft,
			ButtonIcon.RightStickLeft
		},
		{
			InputControlType.RightStickRight,
			ButtonIcon.RightStickRight
		},
		{
			InputControlType.RightStickDown,
			ButtonIcon.RightStickDown
		},
		{
			InputControlType.RightStickUp,
			ButtonIcon.RightStickUp
		},
		{
			InputControlType.DPadUp,
			ButtonIcon.DPadUp
		},
		{
			InputControlType.DPadDown,
			ButtonIcon.DPadDown
		},
		{
			InputControlType.DPadLeft,
			ButtonIcon.DPadLeft
		},
		{
			InputControlType.DPadRight,
			ButtonIcon.DPadRight
		},
		{
			InputControlType.Start,
			ButtonIcon.StartButton
		},
		{
			InputControlType.Menu,
			ButtonIcon.StartButton
		},
		{
			InputControlType.Options,
			ButtonIcon.StartButton
		},
		{
			InputControlType.Plus,
			ButtonIcon.StartButton
		},
		{
			InputControlType.Select,
			ButtonIcon.BackButton
		},
		{
			InputControlType.View,
			ButtonIcon.BackButton
		},
		{
			InputControlType.TouchPadButton,
			ButtonIcon.BackButton
		},
		{
			InputControlType.Minus,
			ButtonIcon.BackButton
		},
		{
			InputControlType.None,
			ButtonIcon.None
		}
	};

	[PublicizedFrom(EAccessModifier.Private)]
	public static readonly HashSet<PlayerAction> loggedMissingBindingSources = new HashSet<PlayerAction>();

	public static INGUIAtlas IconAtlas => symbolAtlas;

	public static string GetSpriteName(ButtonIcon _icon)
	{
		if (PlayerInputManager.InputStyleFromSelectedIconStyle() != PlayerInputManager.InputStyle.PS4)
		{
			return buttonIconMapXB[_icon];
		}
		return buttonIconMapPS[_icon];
	}

	public static ButtonIcon GetButtonIconForAction(PlayerAction _action)
	{
		if (_action == null)
		{
			return ButtonIcon.None;
		}
		DeviceBindingSource deviceBindingSource = _action.GetBindingOfType(_forController: true) as DeviceBindingSource;
		if (deviceBindingSource == null)
		{
			if (loggedMissingBindingSources.Add(_action))
			{
				Log.Warning("UIUtils: No device binding source could be found for PlayerAction {0}", _action.Name);
			}
			return ButtonIcon.None;
		}
		if (iconControlMap.TryGetValue(deviceBindingSource.Control, out var value))
		{
			return value;
		}
		Log.Warning("UIUtils: Could not assign a ButtonIcon for device control {0}", deviceBindingSource.Control.ToString());
		return ButtonIcon.None;
	}

	public static void LoadAtlas()
	{
		symbolAtlas = Resources.Load<UIAtlas>("GUI/Prefabs/SymbolAtlas");
	}
}
