<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>DamageTypeFix</AssemblyName>
    <RootNamespace>DamageTypeFix</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Optimize>true</Optimize>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>.\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <SevenDaysToDieDir Condition="'$(SevenDaysToDieDir)'=='' and Exists('C:\Program Files (x86)\Steam\steamapps\common\7 Days to Die - Doom\7DaysToDie.exe')">C:\Program Files (x86)\Steam\steamapps\common\7 Days to Die - Doom</SevenDaysToDieDir>
    <SevenDaysToDieDir Condition="'$(SevenDaysToDieDir)'=='' and Exists('C:\Program Files (x86)\Steam\steamapps\common\7 Days To Die\7DaysToDie.exe')">C:\Program Files (x86)\Steam\steamapps\common\7 Days To Die</SevenDaysToDieDir>
    <HarmonyDll Condition="Exists('$(SevenDaysToDieDir)\Mods\0_TFP_Harmony\0Harmony.dll')">$(SevenDaysToDieDir)\Mods\0_TFP_Harmony\0Harmony.dll</HarmonyDll>
    <CustomParticleLoaderDll Condition="Exists('C:\Program Files (x86)\Steam\steamapps\common\7 Days to Die - Doom\Mods\0-CustomParticleLoader\CustomParticleLoader.dll')">C:\Program Files (x86)\Steam\steamapps\common\7 Days to Die - Doom\Mods\0-CustomParticleLoader\CustomParticleLoader.dll</CustomParticleLoaderDll>
    <CustomParticleLoaderDll Condition="'$(CustomParticleLoaderDll)'=='' and Exists('C:\Program Files (x86)\Steam\steamapps\common\7 Days to Die Dedicated Server\Mods\0-CustomParticleLoader\CustomParticleLoader.dll')">C:\Program Files (x86)\Steam\steamapps\common\7 Days to Die Dedicated Server\Mods\0-CustomParticleLoader\CustomParticleLoader.dll</CustomParticleLoaderDll>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(HarmonyDll)</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(SevenDaysToDieDir)\7DaysToDie_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(SevenDaysToDieDir)\7DaysToDie_Data\Managed\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(SevenDaysToDieDir)\7DaysToDie_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="CustomParticleLoader">
      <HintPath>$(CustomParticleLoaderDll)</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
