using System.Collections.Generic;
using System.ComponentModel;
using Newtonsoft.Json;

namespace Services.Analytics.Events;

public class ServerStartEventData : BaseEventData
{
	public override string EventType => "server_start";

	[JsonProperty(PropertyName = "server_id")]
	[Description("The id of the server")]
	[field: PublicizedFrom(EAccessModifier.Private)]
	public string ServerId { get; set; }

	[Description("The save holding the world state")]
	[JsonProperty(PropertyName = "save_id")]
	[field: PublicizedFrom(EAccessModifier.Private)]
	public string SaveId { get; set; }

	[JsonProperty(PropertyName = "server_start_ts")]
	[Description("Timestamp for when the server started")]
	[field: PublicizedFrom(EAccessModifier.Private)]
	public string ServerStartTimestamp { get; set; }

	[JsonProperty(PropertyName = "server_type")]
	[Description("Type of server (Dedicated, Listen, Offline)")]
	[field: PublicizedFrom(EAccessModifier.Private)]
	public string ServerType { get; set; }

	[JsonProperty(PropertyName = "sandbox_seed")]
	[Description("Unique code generated by the sandbox settings")]
	[field: PublicizedFrom(EAccessModifier.Private)]
	public string SandboxSeed { get; set; }

	[JsonProperty(PropertyName = "sandbox_settings_delta")]
	[field: PublicizedFrom(EAccessModifier.Private)]
	public object SandboxSettingsDelta { get; set; }

	[JsonProperty(PropertyName = "world_name")]
	[Description("Unique id generated when creating the world")]
	[field: PublicizedFrom(EAccessModifier.Private)]
	public string WorldName { get; set; }

	[JsonProperty(PropertyName = "general_settings")]
	[field: PublicizedFrom(EAccessModifier.Private)]
	public Dictionary<string, object> GeneralSettings { get; set; }

	[JsonProperty(PropertyName = "server_mods")]
	[Description("List of mods with any information we can get")]
	[field: PublicizedFrom(EAccessModifier.Private)]
	public object ServerMods { get; set; }
}
