public enum GameInfoBool
{
	IsDedicated,
	IsPasswordProtected,
	ShowFriendPlayerOnMap,
	BuildCreate,
	EACEnabled,
	SanctionsIgnored,
	Architecture64,
	StockSettings,
	StockFiles,
	ModdedConfig,
	RequiresMod,
	AirDropMarker,
	EnemySpawnMode,
	IsPublic,
	AllowSpawnNearBackpack,
	AllowCrossplay,
	BiomeProgression
}
